### PR TITLE
Use a nice terminal for REPL

### PR DESCRIPTION
**Pull request by amasad**
I found that the REPL was hard to use. Originally I wanted to add this to http://repl.it but found that it needs lots of work for RTL. So I used the [terminal emulator](https://github.com/replit/jq-console).
I also used a [Solarized[(http://ethanschoonover.com/solarized) theme for style.

Additional features:
- Line continuation when:
  - The command doesn't compile; or
  - There is a trailing (. Starts a new line with increased indentation.
  - Holding SHIFT + ENTER.
    
- Shortcuts:
  - CNTRL + A: Move to beginning of the line, 
  - CNTRL + E: Move to end.
  - CNTRL + C: Discards current line.
- Move between lines of current prompt by holding down shift.
- Paran matching.

Additionally we can add the editor to the left and have a repl.it or (dr.scheme) like configuration.

### CODE REVIEW

**Comment by nasser** [comment]
I agree that the current REPL is problematic. What you've put together is great! Try keeping Courier New as the font, as it's the only monospace Arabic font freely available that I know of. I'll take a look at this soon. It might make it into Thursday's opening at Eyebeam.

**Comment by amasad** [comment]
Sure.
Now experimenting with having both editor + console.

Where is the Eyebeam opening held? would love to attend.

**Comment by nasser** [comment]
This is the CodeMirror editor I put together: http://repl.qlblang.org/editor.html

The opening is being held in the Eyebeam Main Space, 540 W 21st St. New York, NY 10011, More info here: http://eyebeam.org/events/2012-annual-showcase.

Thanks for your code, man! It looks great!

**Comment by nasser** [comment]
God, bracket matching would be awesome...

**Comment by amasad** [comment]
> The opening is being held in the Eyebeam Main Space, 540 W 21st St. New York, NY 10011, More info here: http://eyebeam.org/events/2012-annual-showcase.

Will try my best to be there.

> God, bracket matching would be awesome...

I have paran matching. are brackets part of the language?

Also, I noticed you were not printing the return value of executing, do you prefer leaving out and just using print?

**Comment by nasser** [comment]
I meant paren matching.

I love printing the return value. There's no good reason that the the current REPL doesn't do it.

**Comment by amasad** [comment]
You  got it.

Also I noticed the page hangs in the game of life example. We should put the interpreter in a web worker. One problem is jx.js, not sure if it works in a web worker. But maybe we can roll our own xhr. Thoughts?

**Comment by nasser** [comment]
Totally. jx.js is basically a hand rolled xhr. It's super super simple. Does it prevent using a web worker?

**Comment by nasser** [comment]
I'm turning in for the night, but I'll be back on early in the morning. Thanks again for your contribution!

**Comment by amasad** [comment]
Pleasure. Will try to squeeze as much tonight.

On Tue, Jan 15, 2013 at 12:13 AM, Ramsey Nasser notifications@github.comwrote:

> I'm turning in for the night, but I'll be back on early in the morning.
> Thanks again for your contribution!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nasser/---/pull/5#issuecomment-12253824.

## 

## 

Amjad Masad

**Comment by amasad** [comment]
# New Changes

## Files

Qlb interpreter, it's parser and primitives now live in `public/qlb`.

## Parser

Parser is pre built and included in `public/qlb/parser.js`. You can build using node.js:

```
npm install
node build_parser.js
```

## Interpreter
- By removing the need to dynamically generate parser there is no need for the init callback.
- Added an overridable `http` adapter just like console.
- Removed jx.js dep.

## Worker
- Game of Life don't hang the page. but streams!! cool stuff!
- Code concerned with worker and messaging is in `js/worker.js` and `js/repl.js`

**Comment by amasad** [comment]
One more thing: Because expressions are returning as results to the REPL. Things like Amthila are returning confusing strings.



We can add عدم to the end of functions like that to indicate that there is no return value intended.

**Comment by nasser** [comment]
I just pushed out some changes that include a faster, animated Game of Life example. It could really use your web worker patch, though. It locks up the UI something awful. Want to take a crack at merging them? I'm going to give it a shot myself later today or tomorrow, but I have to build mosaics for the show right now.

**Comment by amasad** [comment]
You must understand that web workers don't have access to the DOM and very much live in an isolated world with just an async messaging interface to the outside world. so importing Processing.js in the web worker is not possible. We can import it in the main thread via a message and also draw via messages; However this needs a good amount of work and thinking. and in all honesty i'm afraid that you're going to keep updating your branch and implementing features and both branches will very soon diverge beyond merging and everything would be gone to waste. So I'll give it a shot if you're planning to pull after that, no pressure, just let me know.

**Comment by nasser** [comment]
An absolutely epic PR, @amasad. Clean, commented, and solid. A little bit of work got Processing.js working with it too and now everything is awesome.

Thanks so much! I hope you can make it to the opening on Thursday!

**Comment by amasad** [comment]
:clap: :star2:
sorry for the somewhat snarky comment, i really wanted this to make it in and I'm glad it did. good job on the polish and rasm-worker, looks great!

**Comment by nasser** [comment]
Don't worry about it. This PR takes the project from a prototype to a really solid alpha. It's going to make a huge difference. I'm thinking of ways to streamline the writing of library-main.js/library-worker.js, but it works for now.

Thanks again!

**Comment by amasad** [comment]
Don't mention it!
The way I would love it to be is: Qlb core should not be aware of it's JS environment. Be it Node.js, the browser, a worker thread, main thread, rhino, an Arduino running a JS env etc. Furthermore this would make it easier to implement Qlb on top of different languages.
It should be I/O agnostic but have I/O hooks for libraries, i.e. Rasm, maybe in node even a FileSystem library.
JavaScript is similar to that, the core language is I/O agnostic and that's what makes it portable.

**Pull request merged**
