### PR TITLE
Minimize stack trace needed

### PR DESCRIPTION
**Pull request by amasad**
Quick hack. Makes the examples run in safari.

### CODE REVIEW

**Comment by nasser** [comment]
That was amazing! How does that work? I can't see why it would be different from the current implementation.

You are some kind of wizard...

**Comment by amasad** [comment]
haha, it's just the array helpers `map` etc. Adds more functions calls to the stack and are generally slower.

**Comment by nasser** [comment]
Wow. So simple...

**Comment by amasad** [comment]
Yeah, but still it's just a temporary solution. Eventually it has to be trampolined or done asynchronously (`setTimeout`).

**Pull request merged**
